### ISSUE TITLE
The dict does not delete items but put an empty string 

### ISSUE THREAD

**Issue by haidang1201** [ronny-rentner/UltraDict#12]
Hello,
I am currently using your dictionary for my project. 
Then I found a problem when I try to delete an item from the dict. Instead of deleting, the dict replaces the value that needs to be deleted by an empty string and it leads to a bug in my project. 
I am writing a small piece of code to reproduce this behavior as you can find hereafter. Hope it can help you to figure out the problem. 

```python
from UltraDict import UltraDict
import random
import string
letters = string.ascii_lowercase
rand_str =   ''.join(random.choice(letters) for i in range(1000)) 
my_dict = UltraDict()
for i in range(10000):
	my_dict[i] = rand_str
for i in list(my_dict.keys()):
	del my_dict[i]
print (my_dict)
```
and here are the results I got 
`{379: b'', 750: b'', 1121: b'', 1492: b'', 1863: b'', 2234: b'', 2605: b'', 2976: b'', 3347: b'', 3718: b'', 4089: b'', 4460: b'', 4831: b'', 5202: b'', 5573: b'', 5944: b'', 6315: b'', 6686: b'', 7057: b'', 7428: b'', 7799: b'', 8170: b'', 8541: b'', 8912: b'', 9283: b'', 9654: b''}
`

Thank you

**Comment by ronny-rentner** [comment]
Hello @haidang1201!

Many thanks for your bug report. I can confirm this bug. There was indeed an issue when the last change before full dump was a delete. I've committed a fix in the dev branch and I've also taken the change to use your example code as a new unit test.

Please let me know if you still have issues.
