### ISSUE TITLE
very slow when load big dict and eats cpu

### ISSUE THREAD

**Issue by csrgxtu** [ronny-rentner/UltraDict#13]
![image](https://user-images.githubusercontent.com/5053620/179341014-8ab3a697-6515-4d55-886f-6df686b1a96f.png)

![image](https://user-images.githubusercontent.com/5053620/179341033-9260438c-7145-4afc-b6d6-fd62fba89825.png)

**Comment by ronny-rentner** [comment]
How big is your data? It looks like you're trying to load something into memory that is too big.

**Comment by csrgxtu** [comment]
1448641 line of domain and its status, here is some sample:
![image](https://user-images.githubusercontent.com/5053620/179347168-2d4368a4-fc14-4371-9275-b6aaf2951d33.png)

**Comment by ronny-rentner** [comment]
I've quickly created the following example (in lack of your real data)

```python
import time
from UltraDict import UltraDict

ultra = UltraDict(buffer_size=100_000)
normal = {}

runs = 10
inc = 25_000

for j in range(0, runs):
    start = j * inc
    print(f'RUN {j}')
    t0 = time.perf_counter()
    for i in range(start, start + 25_000):
        ultra[i] = 'some random string with some length, and even a bit longer....'
    t1 = time.perf_counter()
    print(f'ultra_ {((t1-t0) * 1000)} ms to load {len(ultra.keys())}')

    t0 = time.perf_counter()
    for i in range(start, start + 25_000):
        normal[i] = 'some random string with some length, and even a bit longer....'
    t1 = time.perf_counter()
    print(f'normal {((t1-t0) * 1000)} ms to load {len(normal.keys())}')

#ultra.print_status()
```

When I run it:
```shell
RUN 0
ultra_ 56.22358497930691 ms to load 25000
normal 1.9243060378357768 ms to load 25000
RUN 1
ultra_ 65.45579800149426 ms to load 50000
normal 2.044418011792004 ms to load 50000
RUN 2
ultra_ 74.15296096587554 ms to load 75000
normal 1.150374999269843 ms to load 75000
RUN 3
ultra_ 86.29285101778805 ms to load 100000
normal 2.73455202113837 ms to load 100000
RUN 4
ultra_ 94.85198301263154 ms to load 125000
normal 1.1220260057598352 ms to load 125000
RUN 5
ultra_ 105.81968497717753 ms to load 150000
normal 1.1432800092734396 ms to load 150000
RUN 6
ultra_ 115.86209799861535 ms to load 175000
normal 3.061134018935263 ms to load 175000
RUN 7
ultra_ 127.77165498118848 ms to load 200000
normal 1.1187770287506282 ms to load 200000
RUN 8
ultra_ 139.1895649721846 ms to load 225000
normal 1.13689003046602 ms to load 225000
RUN 9
ultra_ 155.26454098289832 ms to load 250000
normal 1.1574049713090062 ms to load 250000
```

This performance is more or less in line with the expectations that are also mentioned in the README: https://github.com/ronny-rentner/UltraDict#write-performance

UltraDict is around factor 100 slower on writes than a normal dict.

UltraDict will get slower and slower depending on the buffer_size because once the whole buffer is taken, it has to create a full dump of all the dict contents. This will obviously be slower the bigger the dict is.

It's easy to optimize UltraDict for initial filling with lots of data given that you do not care about other consumers not doing updates in parallel.

```python
import time
from UltraDict import UltraDict

ultra = UltraDict(buffer_size=100_000)
normal = {}
#ultra = {}

runs = 10
inc = 25_000

t0 = time.perf_counter()
with ultra.lock:
    for j in range(0, runs):
        start = j * inc
        print(f'RUN {j}')
        for i in range(start, start + 25_000):
            # Write changes only to internal cache
            ultra.data[i] = 'some random string with some length, and even a bit longer....'

    # Synchronize all inital data once as a full dump
    ultra.dump()

t1 = time.perf_counter()
print(f'ultra_ {((t1-t0) * 1000)} ms to load {len(ultra.keys())}')

t0 = time.perf_counter()
with ultra.lock:
    for j in range(0, runs):
        start = j * inc
        print(f'RUN {j}')
        for i in range(start, start + 25_000):
            # Write changes only to internal cache
            normal[i] = 'some random string with some length, and even a bit longer....'

    # Synchronize all inital data once as a full dump
    ultra.dump()

t1 = time.perf_counter()
print(f'normal {((t1-t0) * 1000)} ms to load {len(ultra.keys())}')

#ultra.print_status()
```

Result:
```shell
RUN 0
RUN 1
RUN 2
RUN 3
RUN 4
RUN 5
RUN 6
RUN 7
RUN 8
RUN 9
ultra_ 23.524981981609017 ms to load 250000
RUN 0
RUN 1
RUN 2
RUN 3
RUN 4
RUN 5
RUN 6
RUN 7
RUN 8
RUN 9
normal 20.08057205239311 ms to load 250000
```

**Comment by ronny-rentner** [comment]
PS: Of course it depends a bit on what you're trying to achieve

**Comment by csrgxtu** [comment]
>UltraDict will get slower and slower depending on the buffer_size because once the whole buffer is taken, it has to create a full dump of all the dict contents. This will obviously be slower the bigger the dict is.

this helps, by specifing the buffer-size param as following:
```Python
udict = UltraDict(buffer_size=2000000)
```
it now loads my big dict faster （which have 1448461 keys)
![image](https://user-images.githubusercontent.com/5053620/179375899-0ea90708-73c9-46b0-8b5c-387096833515.png)

thanks very much @ronny-rentner ,  i should read the README carefully.

**Comment by ronny-rentner** [comment]
Keep in mind that you should balance buffer size with your total data size. In the dev branch README, there are some more considerations regarding buffer sizes: https://github.com/ronny-rentner/UltraDict/tree/dev#memory-management
