### ISSUE TITLE
Duplicate logs

### ISSUE THREAD

**Issue by marianomat** [ronny-rentner/UltraDict#21]
Hello maybe this is a noob question, but I'm having this problem that when using the library some logs gets duplicated.

![image](https://user-images.githubusercontent.com/57268234/201167451-c4806e12-823e-4442-877f-c5d71ba24801.png)

![image](https://user-images.githubusercontent.com/57268234/201167153-505cfe9e-bea1-4000-a507-a7cfca401076.png)

![image](https://user-images.githubusercontent.com/57268234/201167192-c7b51bea-f491-4dee-a3bc-bb6abcd48a95.png)

This is a very basic setup of FastAPI with UltraDict

**Comment by ronny-rentner** [comment]
Hmm, that's interesting. How does your general logging configuration look like?

UltraDict does nothing more than:
`import logging as log`
and then further in the code:
`log.warning('You are running on win32, potentially without locks. Consider setting shared_lock=True')`

Maybe it makes a difference in which order you import FastAPI and UltraDict?

Maybe I need to mark the log messages from UltraDict somehow so they are not influenced by your general log config?

**Comment by marianomat** [comment]
Hello Ronny first thanks for the quick answer, I'm not using any config, just FastAPI and UltraDict, if I comment the Meta() line, I get this logs:

![image](https://user-images.githubusercontent.com/57268234/201395931-18bd269a-9ef7-4524-826a-8cdddfe1e29b.png)

This is all the code I have:

![image](https://user-images.githubusercontent.com/57268234/201396024-ba0562f4-cdfe-46ee-8edf-bf6c9c6d6c9f.png)

When I don't comment that line, I get some logs duplicated:

![image](https://user-images.githubusercontent.com/57268234/201396195-4dc78833-9bb5-4df0-9f74-c8561850adc1.png)

I'm actually doing an app with FastAPI and was testing this library and got the duplicated logs, so I tested in a new minimal FastAPI app (the source is the basic example in their docs) and I could replicate it as shown in the pics.

It also duplicates my own logs, I could reproduce it in a minimal way:

![image](https://user-images.githubusercontent.com/57268234/201398160-16930a02-ae88-4b5d-b7f4-b2c204bc8864.png)

Console:

![image](https://user-images.githubusercontent.com/57268234/201398343-3866e916-85a7-4c0b-97db-8d40e6a14d47.png)

The random error log gets duplicated.

Here is the code if you want to try: 

https://codeshare.io/dwLyNB

Libraries: fastapi[all] and UltraDict.

**Comment by ronny-rentner** [comment]
Well, in your script, you do have logging configuration in lines 7 to 11. I think this is causing your issue. I've tried with a simpler configuration and it works, no duplicated messages:
![image](https://user-images.githubusercontent.com/4419051/201460600-f4f60e9b-2cc9-47e2-a3b9-eab64f64d5c0.png)


As you can see, I've hardcoded "some warning from UltraDict".

**Comment by ronny-rentner** [comment]
PS: If you are on Windows, don't ignore the shared_lock warning. It's true unless you always ever have at most one process writing to the dict at a time.

**Comment by marianomat** [comment]
Hey thanks for the responses, I finally end up using the library with shared_lock enabled, so it never logs the warining message and that way I don't get duplicated logs.

I'm using the dicts to share data between different requests and it's working fine.
