### ISSUE TITLE
support test on python3.7

### ISSUE THREAD

**Issue by zed2015** [ronny-rentner/UltraDict#22]
many program writed by python3.7 , so it is necessary to support python3.7 and test

**Comment by ronny-rentner** [comment]
Hey, do you have any specific use case for UltraDict in Python 3.7? As far as I know, Python 3.7 is end of life. What stops you from upgrading Python to 3.8?

**Comment by zed2015** [comment]
OK， I will upgrade Python to 3.8, thanks
