### ISSUE TITLE
AttributeError: data when updating nested UltraDicts

### ISSUE THREAD

**Issue by Rickkert00** [ronny-rentner/UltraDict#28]
Hi @ronny-rentner, 

I am trying to use nested UltraDicts to communicate between processes. The information flow is structured as follows:
- Data is coming into a regular dict that has the following structure: `info = {'data': {'example': 0}`
- The `example` key is updated frequently
- I have a UltraDict constructed as follows: `ultra_dict = UltraDict(recurse=True)`
- I update the ultra_dict as follows: `ultra_dict.update(info)`, every x seconds
- After 2 or 3 updates, `ultra_dict.update(info)` fails with the following stacktrace: 
```
  File "C:\venv\lib\site-packages\UltraDict\UltraDict.py", line 815, in update
    self[k] = v
  File "C:\venv\lib\site-packages\UltraDict\UltraDict.py", line 849, in __setitem__
    if item.name not in self.recurse_register.data:
AttributeError: data
```

Because of design limitations it is not possible to have the information flow into `ultra_dict` directly. I expect that I should be able to call `ultra_dict.update(info)` consecutively, even if the information in `info` has not changed. 
There is another process that is reading the information out of `ultra_dict`. 

Is this expected behaviour? If so, how should I update the UltraDict such that information is correctly passed through to the other process?

Code to reproduce the issue:
 ```
ultra_dict = UltraDict(recurse=True)
info = {'data': {'example': 0}}
ultra_dict.update(info)
print(ultra_dict)
info['data']['example'] = 1
ultra_dict.update(info)
print(ultra_dict)
info['data']['example'] = 2
ultra_dict.update(info)
```

Python version: 3.8.10
UltraDict version: 0.0.6

**Comment by ronny-rentner** [comment]
Hi, thanks for your report. Unfortunately there was a bug in the cleanup code and the nested UltraDicts were cleaned up too eagerly. This bug has been fixed in the main branch but the fix was not released yet. I'll do that shortly. Would you be able to try the main branch and see if the issue goes away?

**Comment by Rickkert00** [comment]
After updating to the main branch the issue has been resolved! Thank you!
