### ISSUE TITLE
Spelling mistake in readme.md

### ISSUE THREAD

**Issue by githubdontbanmeagain** [ronny-rentner/UltraDict#30]
Didn't want to create a PR because I hate people that want to fix spelling mistakes just to get into the contributor list.

recurse: If True, any nested dict objects will be automaticall wrapped in an UltraDict allowing transparent nested updates.

automaticall -> automatically

**Comment by ronny-rentner** [comment]
Thanks, fixed it in the dev branch, will update main soon.
