### ISSUE TITLE
Suggestion: key-level locking

### ISSUE THREAD

**Issue by rnv812** [ronny-rentner/UltraDict#31]
It would be great to have key-level locking to improve performance for write operations.

The idea is the following:
When we perform write operation (for a specific key), we should lock the entire dict to ensure that other processes don't modify it at the same time. But for this scenario actually we need to lock only specific key and allow other processes to modify other keys at the same time. 

I think in existing implementation (where only changes are applied to shared memory, rather than entire memory overwriting) this is possible.

It is like  `SELECT ... FOR UPDATE` where only affected rows are locked but not entire table of database.

P.S.
My respects for your project.

**Comment by ronny-rentner** [comment]
Hi @rnv812, thanks for your suggestion.

At the moment, there's just one single byte in shared memory for the locking. If we wanted to change this, we'd have to reserve a bigger, dynamic memory space for locking but that seems quite complex.

What you could do right now is using the recurse mode. If you set `recurse=true`, UltraDict will automatically transform every dict value to a child UltraDict which then has it's own lock.

So it could probably look like this:
```
from UltraDict import UltraDict
ultra = UltraDict(recurse=True)
#When you do it like the following, both keys share the lock:
ultra['key1'] = 'value1'
ultra['key2'] = 'value2'
#When you do it like this, each key has its own lock:
ultra['key1'] = { 'value': 'value1' }
ultra['key2'] = { 'value': 'value2' }

#You can now lock only key1 like this:
with ultra['key1'].lock:
    ultra['key1']['value'] = 'some other value'
```

The approach has the disadvantage that all values (that should have a lock) must be wrapped in a dict. You could also do this just for specific keys/values if you wanted. All non-dict-values will be treated normally.

**Comment by rnv812** [comment]
Oh, this approach seems quite appropriate. Thank you for the answer.
