### ISSUE TITLE
Problem updating iterating on values

### ISSUE THREAD

**Issue by hugo3m** [ronny-rentner/UltraDict#8]
Hi! i started using your dictionary in my project however I found a bug while trying to iterate on the dictionary values. Those few lines of code trigger the bug.

![Screenshot from 2022-05-17 12-15-58](https://user-images.githubusercontent.com/58819009/168788847-17738540-4efe-44b3-8bdd-1b291247cd2d.png)
.

It can be solve by applying apply_update before trying to iterate on the values, however the function is already called by the same process before trying to iterate (I added a print) so I do not really understand why is it solving it. However I'm probably going to iterate over keys instead, trying to bypass it by iterating over items but it is not working too :-)

**Comment by ronny-rentner** [comment]
Hi @hugo3m 

Many thanks for your bug report.
This should be easy to fix. I'll look into it later today. I suspect it is happening because I have not implement the __iter__() method yet.

**Comment by hugo3m** [comment]
Thank you for your quick reply, I look forward to reading your update

**Comment by ronny-rentner** [comment]
As suspected, it was the missing `__iter__()` method.
Please check the `dev` branch and let me know if this fixes your problem.

**Comment by ronny-rentner** [comment]
Thanks a lot for your feedback and your offer. Much appreciated!

Though, I already took the chance to create a new unit test for this issue. It's in the commit above. ;)
